### ISSUE TITLE
Update hard-coded genre count

### ISSUE THREAD

**Issue by jasontyu** [officebeatz/OfficeBeatz2#77]

**Comment by mac-stark** [comment]
![NewGenreCount](https://user-images.githubusercontent.com/49796787/80151159-98de3500-8587-11ea-8102-8927d094ccce.PNG)

**Comment by jasontyu** [comment]
When fixing this, make sure to add both "Hip-Hop" and "Hip Hop" when marking the hip hop checkbox.

**Comment by garrettbolter** [comment]
We need to tie the new boxes (labels & inputs) to the backend for form submission
